create table covid19details(
	iso_code varchar(24) comment '國碼',
    continent varchar(24) comment '洲名',
    location varchar(24) comment '國家',
    date_t date comment '統計日期',
    total_cases int default 0 comment '總確診數',
    new_cases int default 0 comment '新增確診數',
    new_cases_smoothed float(10,2) default 0.0 comment '七天移動平均新增確診數',
    total_deaths int default 0 comment '總死亡數',
    new_deaths int default 0 comment '新增死亡數',
    new_deaths_smoothed float(10,2) default 0.0 comment '七天移動平均新增死亡數',
    total_cases_per_million float(10,2) default 0.0 comment '每百萬人確診數',
    total_deaths_per_million float(10,2) default 0.0 comment '每百萬人死亡數',
    reproduction_rate float(10,2) default 0.0 comment '傳染率',
    new_tests int default 0 comment '新增檢驗件數',
	total_tests int default 0 comment '總檢驗件數',
    total_tests_per_thousand float(10,2) default 0.0 comment '每千人檢驗件數',
    new_tests_smoothed float(10,2) default 0.0 comment '七天移動平均新增檢驗件數',
    positive_rate float(10,2) default 0.0 comment '陽性率',
    tests_per_case float(10,2) default 0.0 comment '每確診案例相對檢驗數量',
    total_vaccinations int default 0 comment '疫苗總接種總劑數',
    people_fully_vaccinated int default 0 comment '疫苗總接種人數',
    new_vaccinations varchar(36) comment '疫苗新增接種劑數',
    new_vaccinations_smoothed float(10,2) default 0.0 comment '七天移動平均疫苗新增接種劑數',
    total_vaccinations_per_hundred float(10,2) default 0.0 comment '每百人接種疫苗劑數',
    people_fully_vaccinated_per_hundred float(10,2) default 0.0 comment '每百人接種疫苗人數',
    stringency_index float(10,2) default 0.0 comment '疫情控管指數',
    population int default 0 comment '總人口數',
    median_age float(6,2) default 0.0 comment '中位數年紀',
    aged_70_older float(5,2) default 0.0 comment '70歲以上人口比例',
    life_expectancy float(6,2) default 0.0 comment '平均壽命',
    Recovered float(10,2) default 0.0 comment '解除隔離數',
    Unblock float(10,2) default 0.0 comment '解封指數'
);
drop table covid19details;